import type {
  User,
  Account,
  Transaction,
  Insight,
  MonthlySummary,
  CategorySummary,
  DailySpending,
} from "@/types";

export const mockUser: User = {
  id: "user-1",
  name: "Juani",
  email: "juani@email.com",
  currency: "PEN",
  savingsGoal: 500,
  payday: 15,
};

export const mockAccounts: Account[] = [
  {
    id: "acc-1",
    name: "BCP Sueldo",
    type: "checking",
    balance: 2340.0,
    currency: "PEN",
    color: "#1B4F9B",
    icon: "🏦",
  },
  {
    id: "acc-2",
    name: "Ahorros BCP",
    type: "savings",
    balance: 1200.0,
    currency: "PEN",
    color: "#10B981",
    icon: "🐷",
  },
  {
    id: "acc-3",
    name: "Yape",
    type: "digital",
    balance: 180.0,
    currency: "PEN",
    color: "#7C3AED",
    icon: "💜",
  },
  {
    id: "acc-4",
    name: "Efectivo",
    type: "cash",
    balance: 95.0,
    currency: "PEN",
    color: "#D97706",
    icon: "💵",
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "t-1",
    type: "income",
    amount: 3200.0,
    description: "Sueldo quincenal",
    merchant: "Empresa SAC",
    category: "Sueldo",
    categoryId: "sueldo",
    accountId: "acc-1",
    accountName: "BCP Sueldo",
    date: "2025-05-15",
    currency: "PEN",
  },
  {
    id: "t-2",
    type: "expense",
    amount: 45.0,
    description: "Almuerzo en Wong",
    merchant: "Wong",
    category: "Alimentación",
    categoryId: "alimentacion",
    accountId: "acc-3",
    accountName: "Yape",
    date: "2025-05-15",
    currency: "PEN",
  },
  {
    id: "t-3",
    type: "expense",
    amount: 18.5,
    description: "Taxi a la oficina",
    merchant: "InDriver",
    category: "Transporte",
    categoryId: "transporte",
    accountId: "acc-3",
    accountName: "Yape",
    date: "2025-05-15",
    currency: "PEN",
  },
  {
    id: "t-4",
    type: "expense",
    amount: 320.0,
    description: "Compras de la semana",
    merchant: "Plaza Vea",
    category: "Supermercado",
    categoryId: "supermercado",
    accountId: "acc-1",
    accountName: "BCP Sueldo",
    date: "2025-05-14",
    currency: "PEN",
  },
  {
    id: "t-5",
    type: "expense",
    amount: 29.9,
    description: "Netflix",
    merchant: "Netflix",
    category: "Entretenimiento",
    categoryId: "entretenimiento",
    accountId: "acc-1",
    accountName: "BCP Sueldo",
    date: "2025-05-14",
    currency: "PEN",
  },
  {
    id: "t-6",
    type: "expense",
    amount: 12.0,
    description: "Delivery de pizza",
    merchant: "Rappi",
    category: "Alimentación",
    categoryId: "alimentacion",
    accountId: "acc-3",
    accountName: "Yape",
    date: "2025-05-13",
    currency: "PEN",
  },
  {
    id: "t-7",
    type: "expense",
    amount: 55.0,
    description: "Consulta médica",
    merchant: "Clínica San Pablo",
    category: "Salud",
    categoryId: "salud",
    accountId: "acc-1",
    accountName: "BCP Sueldo",
    date: "2025-05-13",
    currency: "PEN",
  },
  {
    id: "t-8",
    type: "expense",
    amount: 25.0,
    description: "Pasajes Metropolitano",
    merchant: "Metropolitano",
    category: "Transporte",
    categoryId: "transporte",
    accountId: "acc-4",
    accountName: "Efectivo",
    date: "2025-05-12",
    currency: "PEN",
  },
  {
    id: "t-9",
    type: "expense",
    amount: 89.9,
    description: "Blusa y pantalón",
    merchant: "Ripley",
    category: "Ropa",
    categoryId: "ropa",
    accountId: "acc-1",
    accountName: "BCP Sueldo",
    date: "2025-05-12",
    currency: "PEN",
  },
  {
    id: "t-10",
    type: "income",
    amount: 400.0,
    description: "Proyecto web freelance",
    merchant: "Cliente particular",
    category: "Freelance",
    categoryId: "freelance",
    accountId: "acc-1",
    accountName: "BCP Sueldo",
    date: "2025-05-11",
    currency: "PEN",
  },
  {
    id: "t-11",
    type: "expense",
    amount: 8.5,
    description: "Café en Starbucks",
    merchant: "Starbucks",
    category: "Alimentación",
    categoryId: "alimentacion",
    accountId: "acc-3",
    accountName: "Yape",
    date: "2025-05-11",
    currency: "PEN",
  },
  {
    id: "t-12",
    type: "expense",
    amount: 150.0,
    description: "Luz y agua",
    merchant: "Enel / SEDAPAL",
    category: "Servicios",
    categoryId: "servicios",
    accountId: "acc-1",
    accountName: "BCP Sueldo",
    date: "2025-05-10",
    currency: "PEN",
  },
  {
    id: "t-13",
    type: "expense",
    amount: 35.0,
    description: "Cine con amigos",
    merchant: "Cinemark",
    category: "Entretenimiento",
    categoryId: "entretenimiento",
    accountId: "acc-3",
    accountName: "Yape",
    date: "2025-05-10",
    currency: "PEN",
  },
  {
    id: "t-14",
    type: "expense",
    amount: 22.0,
    description: "Almuerzo menú",
    merchant: "Restaurante El Buen Sabor",
    category: "Alimentación",
    categoryId: "alimentacion",
    accountId: "acc-4",
    accountName: "Efectivo",
    date: "2025-05-09",
    currency: "PEN",
  },
  {
    id: "t-15",
    type: "expense",
    amount: 180.0,
    description: "Curso de diseño online",
    merchant: "Domestika",
    category: "Educación",
    categoryId: "educacion",
    accountId: "acc-1",
    accountName: "BCP Sueldo",
    date: "2025-05-09",
    currency: "PEN",
  },
  {
    id: "t-16",
    type: "expense",
    amount: 45.0,
    description: "Taxi Aeropuerto",
    merchant: "Uber",
    category: "Transporte",
    categoryId: "transporte",
    accountId: "acc-3",
    accountName: "Yape",
    date: "2025-05-08",
    currency: "PEN",
  },
  {
    id: "t-17",
    type: "expense",
    amount: 68.5,
    description: "Compras farmacia",
    merchant: "Mifarma",
    category: "Salud",
    categoryId: "salud",
    accountId: "acc-3",
    accountName: "Yape",
    date: "2025-05-08",
    currency: "PEN",
  },
  {
    id: "t-18",
    type: "expense",
    amount: 15.0,
    description: "Desayuno",
    merchant: "Panadería La Dulce",
    category: "Alimentación",
    categoryId: "alimentacion",
    accountId: "acc-4",
    accountName: "Efectivo",
    date: "2025-05-07",
    currency: "PEN",
  },
  {
    id: "t-19",
    type: "expense",
    amount: 220.0,
    description: "Compras supermercado",
    merchant: "Metro",
    category: "Supermercado",
    categoryId: "supermercado",
    accountId: "acc-1",
    accountName: "BCP Sueldo",
    date: "2025-05-06",
    currency: "PEN",
  },
  {
    id: "t-20",
    type: "expense",
    amount: 40.0,
    description: "Regalo de cumpleaños",
    merchant: "Paris",
    category: "Regalos",
    categoryId: "regalos",
    accountId: "acc-3",
    accountName: "Yape",
    date: "2025-05-05",
    currency: "PEN",
  },
  {
    id: "t-21",
    type: "expense",
    amount: 250.0,
    description: "Renta cuarto",
    merchant: "Propietario",
    category: "Hogar",
    categoryId: "hogar",
    accountId: "acc-1",
    accountName: "BCP Sueldo",
    date: "2025-05-05",
    currency: "PEN",
  },
  {
    id: "t-22",
    type: "expense",
    amount: 11.9,
    description: "Spotify",
    merchant: "Spotify",
    category: "Entretenimiento",
    categoryId: "entretenimiento",
    accountId: "acc-1",
    accountName: "BCP Sueldo",
    date: "2025-05-04",
    currency: "PEN",
  },
  {
    id: "t-23",
    type: "expense",
    amount: 33.0,
    description: "Manicure y pedicure",
    merchant: "Salón Bella",
    category: "Belleza",
    categoryId: "belleza",
    accountId: "acc-3",
    accountName: "Yape",
    date: "2025-05-03",
    currency: "PEN",
  },
  {
    id: "t-24",
    type: "expense",
    amount: 75.0,
    description: "Libros universitarios",
    merchant: "Librería El Estudiante",
    category: "Educación",
    categoryId: "educacion",
    accountId: "acc-4",
    accountName: "Efectivo",
    date: "2025-05-02",
    currency: "PEN",
  },
  {
    id: "t-25",
    type: "income",
    amount: 50.0,
    description: "Transferencia de mamá",
    merchant: "Familia",
    category: "Otros ingresos",
    categoryId: "otros_ingresos",
    accountId: "acc-3",
    accountName: "Yape",
    date: "2025-05-01",
    currency: "PEN",
  },
];

export const mockMonthlySummary: MonthlySummary = {
  month: "Mayo",
  year: 2025,
  totalIncome: 3650.0,
  totalExpenses: 1847.2,
  balance: 1802.8,
  savingsGoal: 500,
  savingsAchieved: 347.0,
};

export const mockCategorySummaries: CategorySummary[] = [
  {
    categoryId: "alimentacion",
    categoryName: "Alimentación",
    categoryIcon: "🍽️",
    categoryColor: "#F97316",
    total: 103.0,
    transactionCount: 5,
    percentage: 18.5,
  },
  {
    categoryId: "supermercado",
    categoryName: "Supermercado",
    categoryIcon: "🛒",
    categoryColor: "#EAB308",
    total: 540.0,
    transactionCount: 2,
    percentage: 17.2,
  },
  {
    categoryId: "hogar",
    categoryName: "Hogar",
    categoryIcon: "🏠",
    categoryColor: "#14B8A6",
    total: 250.0,
    transactionCount: 1,
    percentage: 13.5,
  },
  {
    categoryId: "educacion",
    categoryName: "Educación",
    categoryIcon: "📚",
    categoryColor: "#6366F1",
    total: 255.0,
    transactionCount: 2,
    percentage: 13.8,
  },
  {
    categoryId: "servicios",
    categoryName: "Servicios",
    categoryIcon: "⚡",
    categoryColor: "#64748B",
    total: 150.0,
    transactionCount: 1,
    percentage: 8.1,
  },
  {
    categoryId: "transporte",
    categoryName: "Transporte",
    categoryIcon: "🚗",
    categoryColor: "#3B82F6",
    total: 88.5,
    transactionCount: 3,
    percentage: 4.8,
  },
  {
    categoryId: "salud",
    categoryName: "Salud",
    categoryIcon: "💊",
    categoryColor: "#EF4444",
    total: 123.5,
    transactionCount: 2,
    percentage: 6.7,
  },
  {
    categoryId: "entretenimiento",
    categoryName: "Entretenimiento",
    categoryIcon: "🎬",
    categoryColor: "#A855F7",
    total: 76.8,
    transactionCount: 3,
    percentage: 4.2,
  },
  {
    categoryId: "ropa",
    categoryName: "Ropa",
    categoryIcon: "👗",
    categoryColor: "#EC4899",
    total: 89.9,
    transactionCount: 1,
    percentage: 4.9,
  },
  {
    categoryId: "regalos",
    categoryName: "Regalos",
    categoryIcon: "🎁",
    categoryColor: "#7C3AED",
    total: 40.0,
    transactionCount: 1,
    percentage: 2.2,
  },
  {
    categoryId: "belleza",
    categoryName: "Belleza",
    categoryIcon: "💅",
    categoryColor: "#F43F5E",
    total: 33.0,
    transactionCount: 1,
    percentage: 1.8,
  },
];

export const mockInsights: Insight[] = [
  {
    id: "ins-1",
    type: "warning",
    title: "Gastos en alimentación altos",
    message:
      "Este mes llevas S/ 103 en comida fuera de casa. En abril gastaste S/ 82. ¿Qué tal cocinar más en casa?",
    emoji: "🍽️",
    actionLabel: "Ver desglose",
    actionUrl: "/categories",
  },
  {
    id: "ins-2",
    type: "success",
    title: "¡Vas muy bien con el ahorro!",
    message:
      "Ya llevas S/ 347 ahorrados de tu meta de S/ 500. ¡Solo te faltan S/ 153 para completarla!",
    emoji: "🎉",
  },
  {
    id: "ins-3",
    type: "info",
    title: "Suscripciones activas",
    message:
      "Tienes Netflix (S/ 29.90) y Spotify (S/ 11.90). En total S/ 41.80 al mes en entretenimiento digital.",
    emoji: "📱",
  },
  {
    id: "ins-4",
    type: "alert",
    title: "Próximo pago: Renta",
    message: "Tu renta de S/ 250 vence el 5 de junio. Asegúrate de tener fondos en tu cuenta BCP.",
    emoji: "🏠",
    actionLabel: "Revisar cuentas",
    actionUrl: "/accounts",
  },
  {
    id: "ins-5",
    type: "success",
    title: "Ingreso extra este mes",
    message: "Recibiste S/ 400 de tu proyecto freelance. ¡Buen trabajo! Considera ahorrar una parte.",
    emoji: "💪",
  },
  {
    id: "ins-6",
    type: "info",
    title: "Mayor gasto: Educación",
    message:
      "Invertiste S/ 255 en educación este mes. Eso es una excelente inversión en tu futuro.",
    emoji: "📚",
  },
];

export const mockDailySpending: DailySpending[] = [
  { date: "2025-05-09", label: "Vie", amount: 202.0 },
  { date: "2025-05-10", label: "Sab", amount: 55.0 },
  { date: "2025-05-11", label: "Dom", amount: 8.5 },
  { date: "2025-05-12", label: "Lun", amount: 114.9 },
  { date: "2025-05-13", label: "Mar", amount: 67.0 },
  { date: "2025-05-14", label: "Mie", amount: 349.9 },
  { date: "2025-05-15", label: "Jue", amount: 63.5 },
];

export const mockPreviousMonthSummary: MonthlySummary = {
  month: "Abril",
  year: 2025,
  totalIncome: 3200.0,
  totalExpenses: 1680.5,
  balance: 1519.5,
  savingsGoal: 500,
  savingsAchieved: 420.0,
};
